### PR TITLE
#197 - Payment fields - Checkout page

### PR DESCRIPTION
**Pull request by garthbrantley**

### CODE REVIEW

**Comment by garthbrantley** [comment]
@eugene-shab We found a few issues in a few different scenarios:

# Scenario 1 - 

- Config 1
- 3DS2 enabled
- Using a 3DS2 test card for frictionless flow, successful PA transaction ()
  - (We believe the same issues occurs when using challenge flow / challenge card)
- 3DS2 authentication completes
- Payment transaction is declined (because Test Gateway doesn't support 3DS2 test cards)
- Spinner spins
- Page is redirected to the Shipping step of checkout

## What should happen: "Transaction has been declined. Please try again later." should be displayed. (See videos of how the extension worked in past with Spreedly iframe & 3DS2).

# Scenario 2

- Config 1
- 3DS2 disbaled
- Using a regular test card (like 4111111111111111)
- Payment transaction is successful
- Nothing happens, customer still on checkout page

## What should happen: Customer redirected to thank you page, etc

**Review by garthbrantley — COMMENTED** [review]
@eugene-shab I noticed that the error message which is displayed when payment transaction fails disappeared on its own rather quickly. Is this normal for other payment extensions?

**Comment by eugene-shab** [comment]
> @eugene-shab I noticed that the error message which is displayed when payment transaction fails disappeared on its own rather quickly. Is this normal for other payment extensions?

By default it have timeout 3 sec.

**Comment by garthbrantley** [comment]
@eugene-shab For reference this is the message we are discussing:

image

**Pull request merged**
